name = "Aspasia"
uuid = "51c77908-4dc3-11e9-0c72-cd24fbe21d96"
authors = ["Chris Coey <coey.chris@gmail.com>"]
repo = "https://github.com/chriscoey/Aspasia.jl.git"
version = "0.0.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[compat]
MathOptInterface = "0.10, 1"
julia = "1.6"

[extras]
GLPK = "60bf3e95-4087-53dc-ae20-288a0d20c6a6"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["GLPK", "Test"]
